### ISSUE TITLE
Rendu BANO v2 en prod. : remarques

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#208]
Hello, 

Comme promis, et un peu en vrac, quelques remarques et questions.
NB : je prends comme réf. la légende BANO du wiki (https://wiki.openstreetmap.org/wiki/FR:France/WikiProject_Base_Adresses_Nationale_Ouverte_(BANO)#L.C3.A9gende)

- [ ] Numéros en [5|6]XXX (rouges ou bleus) : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.81492/1.13984
![Screenshot_2020-11-11 https tile openstreetmap fr](https://user-images.githubusercontent.com/36087963/98864359-0ab99580-246a-11eb-85e6-2cf0e599fa28.png)
- [ ] Numéros en rouge avec pb de nom de voie ou distance trop grande avec osm pour rapprochement ? : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.80512/1.15978
![Screenshot_2020-11-11 https tile openstreetmap fr2](https://user-images.githubusercontent.com/36087963/98864765-b19e3180-246a-11eb-900c-3eaafce5c14d.png)
- [ ] Numéros en rouge avec  distance trop grande avec osm pour rapprochement ? https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.79578/1.13119
![Screenshot_2020-11-11 https tile openstreetmap fr3](https://user-images.githubusercontent.com/36087963/98866113-bd8af300-246c-11eb-8b39-49222a2a0e77.png)
- [ ] Numéros bien présents dans OSM mais pas rapprochés (pas de vert) : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.78244/1.13781
![Screenshot_2020-11-11 https tile openstreetmap fr4](https://user-images.githubusercontent.com/36087963/98866875-ed86c600-246d-11eb-8273-d6442b4e85d2.png)
- [ ] la coloration des voies litigieuses semble avoir disparu ou le signalement est bizarre : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.79237/1.13012 alors que https://www.openstreetmap.org/way/68966293
![Screenshot_2020-11-11 https tile openstreetmap fr5](https://user-images.githubusercontent.com/36087963/98867846-8d911f00-246f-11eb-9354-eae51ab9357c.png)

C'est tout ce que je ne comprends pas pour l'instant. Après tout, je n'ai peut-être effectivement rien compris :/

PS : faut vraiment virer les 5000 et suivants : ça pollue le rendu et complexifie les corrections :(

HTH

**Comment by cquest** [comment]
J'ai identifié la cause principale des incohérences : cumul_adresses contient 4 sources (OSM, BAL, BAN et CADASTRE)

Avec BANOv1, il y avait OSM, OPENDATA, CADASTRE... mais la feuille de style n'a pas été adaptée, je vais la corriger car là rien n'est bien cohérent :(

**Comment by Olyon** [comment]
> Hello,
> 
> Comme promis, et un peu en vrac, quelques remarques et questions.
> NB : je prends comme réf. la légende BANO du wiki (https://wiki.openstreetmap.org/wiki/FR:France/WikiProject_Base_Adresses_Nationale_Ouverte_(BANO)#L.C3.A9gende)
> 
>     * [ ]  Numéros en [5|6]XXX (rouges ou bleus) : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.81492/1.13984
>       ![Screenshot_2020-11-11 https tile openstreetmap fr](https://user-images.githubusercontent.com/36087963/98864359-0ab99580-246a-11eb-85e6-2cf0e599fa28.png)
> 
>     * [ ]  Numéros en rouge avec pb de nom de voie ou distance trop grande avec osm pour rapprochement ? : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.80512/1.15978
>       ![Screenshot_2020-11-11 https tile openstreetmap fr2](https://user-images.githubusercontent.com/36087963/98864765-b19e3180-246a-11eb-900c-3eaafce5c14d.png)

Pour le cadastre en bleu, il y a rapprochement, mais dans la BAN, il y a 2 noms de rue differents : 
Impasse Jean Baptiste Fragonard https://adresse.data.gouv.fr/explore/commune/87001/voie/87001_0357
impasse Jean Honore Fragonard https://adresse.data.gouv.fr/explore/commune/87001/voie/87001_1iwizu
donc c'est normale que l'on est du rouge et du bleu.

> 
>     * [ ]  Numéros en rouge avec  distance trop grande avec osm pour rapprochement ? https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.79578/1.13119
>       ![Screenshot_2020-11-11 https tile openstreetmap fr3](https://user-images.githubusercontent.com/36087963/98866113-bd8af300-246c-11eb-8b39-49222a2a0e77.png)
> 
un peu comme précedemment, cadastre : Avenue Pasteur et BAN : Avenue Louis Pasteur (https://adresse.data.gouv.fr/explore/commune/87001/voie/87001_0600/numero/19)
Mais là il n'y a en qu'un nom de rue dans la BAN avec le code fantoir indiqué.
Il faudrait je pense supprimer toutes les adresses du cadastre de BANO, ils sont déjà present dans la BAN qui fait le tri de ce qu'il faut garder. ça réglerait le problème des pseudo numero en 5000 et 6000.

>     * [ ]  Numéros bien présents dans OSM mais pas rapprochés (pas de vert) : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.78244/1.13781
>       ![Screenshot_2020-11-11 https tile openstreetmap fr4](https://user-images.githubusercontent.com/36087963/98866875-ed86c600-246d-11eb-8273-d6442b4e85d2.png)
> 
Pas de nom de rue pour cette adresse seulement un addr:place=Tabaillou et ça ne doit pas être gérer par BANO.

>     * [ ]  la coloration des voies litigieuses semble avoir disparu ou le signalement est bizarre : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.79237/1.13012 alors que https://www.openstreetmap.org/way/68966293
>       ![Screenshot_2020-11-11 https tile openstreetmap fr5](https://user-images.githubusercontent.com/36087963/98867846-8d911f00-246f-11eb-9354-eae51ab9357c.png)
> 
dans le wiki : Pour les voies (géolocalisées sur leur tracé par un nœud plus ou moins central mais qui n'est pas un point d'adresse) :
    ● nom de voie bleu ciel : voie sans adresse rapprochée avec FANTOIR (dans OSM ne figurera que la voie, souvent un chemin ou sentier pédestre, mais aucun nœud d'adresse) ;
donc pour moi le rendu est logique
> 
> C'est tout ce que je ne comprends pas pour l'instant. Après tout, je n'ai peut-être effectivement rien compris :/
> 
> PS : faut vraiment virer les 5000 et suivants : ça pollue le rendu et complexifie les corrections :(
> 
> HTH

**Comment by cquest** [comment]
Les changements :
- suppression des données de la source CADASTRE (donc plus de 5000+)
- l'entourage sur les adresses avec un manque n'est plus affiché si elles correspondent à un lieu-dit présent dans OSM (et rapproché)

Vu que cela impacte complètement le rendu, on peut faire un reset de cette issue ;)

**Comment by deuzeffe** [comment]
Hello @Olyon,

Merci pour tes commentaires détaillés et circonstanciés.

> Pour le cadastre en bleu, il y a rapprochement, mais dans la BAN, il y a 2 noms de rue differents :
> Impasse Jean Baptiste Fragonard https://adresse.data.gouv.fr/explore/commune/87001/voie/87001_0357
> impasse Jean Honore Fragonard https://adresse.data.gouv.fr/explore/commune/87001/voie/87001_1iwizu
> donc c'est normale que l'on est du rouge et du bleu.

Pour une fois, c'est cadastre/FANTOIR qui a raison.

> un peu comme précédemment, cadastre : Avenue Pasteur et BAN : Avenue Louis Pasteur (https://adresse.data.gouv.fr/explore/commune/87001/voie/87001_0600/numero/19)
> Mais là il n'y a en qu'un nom de rue dans la BAN avec le code fantoir indiqué.

C'est encore Cadastre qui remporte un panier garni.

> Il faudrait je pense supprimer toutes les adresses du cadastre de BANO, ils sont déjà present dans la BAN qui fait le tri de ce qu'il faut garder. ça réglerait le problème des pseudo numero en 5000 et 6000.

Oh.que.oui.

> Pas de nom de rue pour cette adresse seulement un addr:place=Tabaillou et ça ne doit pas être gérer par BANO.

C'est ce que j'ai pensé aussi.

> dans le wiki : Pour les voies (géolocalisées sur leur tracé par un nœud plus ou moins central mais qui n'est pas un point d'adresse) :
> ● nom de voie bleu ciel : voie sans adresse rapprochée avec FANTOIR (dans OSM ne figurera que la voie, souvent un chemin ou sentier pédestre, mais aucun nœud d'adresse) ;
> donc pour moi le rendu est logique

C'est pas clair, parfois ça correspond avec la légende, parfois non. J'investigue ;)

@cquest je ferme le ticket, j'en ouvrirai un si besoin pour le rendu v2.1 ;P
